import wx

MAIN_TITLE = wx.Font(26, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD)
SUB_TITLE = wx.Font(23, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD)
SUB_SUB_TITLE = wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL)

MAIN_MENUE_ITEM = wx.Font(20, wx.DECORATIVE, wx.FONTSTYLE_NORMAL, wx.NORMAL)
SUB_MENUE_ITEM = wx.Font(16, wx.DECORATIVE, wx.FONTSTYLE_NORMAL, wx.NORMAL)

TXT_BIG = wx.Font(12, wx.DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD)
TXT_NORMAL = wx.Font(11, wx.DECORATIVE, wx.FONTSTYLE_NORMAL, wx.NORMAL)